### ISSUE TITLE
Asset folder icons are not displaying their correct icons

### ISSUE THREAD

**Issue by elysiaisalive** [erryox/onedark-gmedit#2]
As you can see in the attached image, the folder icons are not the correct ones. Even with new projects this issue persists and is only an issue with this specific theme.

![image](https://user-images.githubusercontent.com/23018312/227390557-10e67b68-569c-4b17-8fad-52acdeff36f5.png)

**Comment by erryox** [comment]
I hope @matheusroberson's PR has fixed this, I haven't used it in quite some time :D

**Comment by elysiaisalive** [comment]
No luck sadly : (
