### ISSUE TITLE
Multi-line tabs height broken

### ISSUE THREAD

**Issue by elysiaisalive** [erryox/onedark-gmedit#4]
Issue: Multi-line tabs are not displaying with proper height and expand when hovered over, covering the entire application.

![image](https://github.com/erryox/onedark-gmedit/assets/23018312/2653e33c-6767-4952-9ff0-bd7a6123b8de)

**Comment by erryox** [comment]
Sorry but I’m no longer maintaining this repository and there are no plans for future updates. Feel free to fork it.
